#!/bin/bash 

#    Copyright 2020 Renzo Davoli
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Debian Official Cloud Images (SID)
BASEDIR=http://cdimage.debian.org/cdimage/cloud/sid/daily/

# get the tag of the latest image
LATESTTAG=$(wget -q -O - $BASEDIR | \
			 grep -o '<a .*href=.*>' | sed -e 's/<a /\n<a /g' | tail -1 | \
			 sed -e 's/<a .*href=['"'"'"]//' -e 's/["'"'"'].*$//' -e 's/\/$//' -e '/^$/ d')

IMAGETAG=debian-sid-nocloud-amd64-daily-
V2TAG=debian-sid-v2-amd64-daily-

# local name of the image
PATHIMG=${IMAGETAG}${LATESTTAG}.qcow2
# url of the image
URLIMG=${BASEDIR}${LATESTTAG}/${PATHIMG}
# local name of the image in raw format (needed to exmpand the root partition)
PATHRAW=${IMAGETAG}${LATESTTAG}.img
# local name of the V2 image
PATHV2=${V2TAG}${LATESTTAG}.qcow2
# hostname 
HOSTNAME=V2-${LATESTTAG}

# do not download the image twice if it is already here
if [ ! -f $PATHIMG ]
then
	wget $URLIMG
fi

# convert to raw
qemu-img convert -f qcow2 -O raw $PATHIMG $PATHRAW
# enlarge the disk image file to 10G
truncate --size=10G $PATHRAW
# trick to update the GPT header
printf "fix\n" | /sbin/parted ---pretend-input-tty $PATHRAW print
# remove the root partition
/sbin/parted -s $PATHRAW rm 1
# compute the free space
PARTDATA=`/sbin/parted -s $PATHRAW unit MB print free | grep "Free Space" | awk '{print $1,$2}' | tail -1`
# create a new partition resizing the file system.
/sbin/parted -s $PATHRAW mkpart / ext4 $PARTDATA
# convert the raw image to the V2 qcow2
qemu-img convert -f raw -O qcow2 $PATHRAW $PATHV2

# remove the temporary raw image
rm -f $PATHRAW

# set hostmame, update/install xterm and xauth, set root passowrd 
#	    get the v2 scripts
#     set the exec bit for scripts
#     generate ssh host keys
#     allow ssh passwd authehtication for users and root
#     create the virtualsquare user and set its password
#     set a fancy prompt for capabilities and vuos environments
virt-sysprep -a $PATHV2 \
		--hostname $HOSTNAME \
		--root-password password:virtualsquare \
		--network \
		--update --install xterm,xauth \
		--run-command 'cd /root; wget https://raw.githubusercontent.com/virtualsquare/virtualsquare.github.io/master/archive/install_scripts/install_packets_for_v2.sh' \
		--run-command 'cd /root; wget https://raw.githubusercontent.com/virtualsquare/virtualsquare.github.io/master/archive/install_scripts/install_v2_projects.sh' \
		--run-command 'cd /root; wget https://raw.githubusercontent.com/virtualsquare/virtualsquare.github.io/master/archive/install_scripts/append_to.bashrc' \
		--run-command 'cd /root; chmod +x install_packets_for_v2.sh install_v2_projects.sh' \
		--run-command 'ssh-keygen -A' \
		--run-command "sed -i 's/^.*PasswordAuthentication.*$/#PasswordAuthentication yes/' /etc/ssh/sshd_config" \
		--run-command "sed -i 's/^.*PermitRootLogin.*$/PermitRootLogin Yes/' /etc/ssh/sshd_config" \
		--run-command 'adduser --disabled-password --gecos "" virtualsquare' \
		--run-command 'echo "virtualsquare:virtualsquare" | chpasswd' \
		--run-command 'cat /root/append_to.bashrc >> /home/virtualsquare/.bashrc'

